services:
  # For release builds
  tourist-main:
    build:
      context: .
      dockerfile: Dockerfile.main
    container_name: tourist

  # For running tourist locally
  # This container and the tourist package is built from 
  # the source code on your local machine.
  tourist-local:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: tourist-local
    hostname: tourist-local
    ports:
      - 8000:8000

  # Deploy tourist into AWS using Terraform/SAM.
  # IMPORTANT: By default, state is managed locally under `./data/statefile`
  # TODO/Contribution: Convert to tf module
  # TODO/Contribution: Allow for "backend" customizations with tfconfig
  # TODO/Contribution: Change entrypoint to auto-deploy the infra; maybe through a shell script?
  sam-deploy:
    build:
      dockerfile: Dockerfile.sam
    container_name: sam-deploy
    working_dir: /build/terraform/aws
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # docker
      - ./terraform/aws:/build/terraform/aws  # terraform code
      - ./data/statefile:/build/terraform/statefile  # statefile!
    env_file:
      - .env.aws  # need AWS credentials to deploy
    environment:
      - SAM_CLI_TELEMETRY=0
    entrypoint: sleep 8h