FROM python:3.13-bullseye

ARG MODE=mcp
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DISPLAY=:99 \
    TOURIST_VERSION=local

COPY . .

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y xauth xvfb && \
    pip install --no-cache-dir .[${MODE}] && \
    python -m patchright install --with-deps chrome

ENTRYPOINT [ "python", "-m", "tourist" ]
